version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    user: "root:root"
    networks:
      - shark

networks:
  shark:
    name: shark
    external: true