repos:
- repo: "https://github.com/astral-sh/ruff-pre-commit"
  rev: "v0.1.5"
  hooks:
  - id: "ruff"
    name: "Run the Ruff linter"
    types_or: ["python", "pyi"]
    args: ["--fix"]
    files: "^backend/sharkservers/.*"
  - id: "ruff-format"
    name: "Run the Ruff formatter"
    types_or: ["python", "pyi"]
    files: "^backend/sharkservers/.*"

- repo: "https://github.com/python-poetry/poetry"
  rev: "1.7.0"
  hooks:
  - id: "poetry-lock"
    stages: ["push"]
    name: "Run Poetry lock hook"
    files: "^backend/sharkservers/.*"
  - id: "poetry-check"
    stages: ["push"]
    name: "Run Poetry check hook"
    files: "^backend/sharkservers/.*"

- repo: local
  hooks:
  - id: generate-openapi-file
    name: Generate the JS client
    language: script
    entry: ./scripts/generate-openapi-file.sh
    files: "^backend/sharkservers/.*"
