services:
  app:
    build:
      context: api/
      dockerfile: Dockerfile
    cpus: '0.50'
    mem_limit: 1g
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8080 --ws  wsproto --proxy-headers
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/app/
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - shark
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    restart: always
    ports:
      - "5432:5432"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
  jailbreak_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=jailbreak_db
      - POSTGRES_USER=jailbreak_user
      - POSTGRES_PASSWORD=jailbreak_password
    restart: always
    expose:
      - "5432:5432"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
  jailbreak_app:
    build:
      context: sourcemod_api/
      dockerfile: Dockerfile
    cpus: '0.50'
    mem_limit: 1g
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8081 --proxy-headers
    ports:
      - "8081:8081"
    volumes:
      - ./sourcemod_api/:/app/
    env_file:
      - ./sourcemod_api/.env
    depends_on:
      jailbreak_db:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - shark

networks:
  shark:
