services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sharkservers_app
    command: uvicorn sharkservers.main:app --reload --host 0.0.0.0 --port 8080 --ws  wsproto --proxy-headers
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - shark
  db:
    image: postgres:15.1
    container_name: sharkservers_db
    environment:
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    restart: always
    ports:
      - "5432:5432"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    container_name: sharkservers_redis
    restart: always
    expose:
      - "6379:6379"
    networks:
      - shark
    healthcheck:
      test: "exit 1"

networks:
  shark:
    name: shark
    external: true

volumes:
  local_pgdata: