services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    cpus: '0.50'
    mem_limit: 1g
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8080 --ws  wsproto --proxy-headers
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    restart: always
    networks:
      - shark
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=shark_db
      - POSTGRES_USER=shark_user
      - POSTGRES_PASSWORD=shark_password
    restart: always
    ports:
      - "5432:5432"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    restart: always
    expose:
      - "6379:6379"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
  jailbreak_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=jailbreak_db
      - POSTGRES_USER=jailbreak_user
      - POSTGRES_PASSWORD=jailbreak_password
    restart: always
    expose:
      - "5432:5432"
    networks:
      - shark
    healthcheck:
      test: "exit 1"
  jailbreak_app:
    build:
      context: ../fastapi-sourcemod/
      dockerfile: Dockerfile
    cpus: '0.50'
    mem_limit: 1g
    command: uvicorn fastapi_sourcemod.main:app --reload --host 0.0.0.0 --port 8081 --proxy-headers
    ports:
      - "8081:8081"
    volumes:
      - ../fastapi-sourcemod/:/app/

    environment:
      - DATABASE_URL=postgresql+asyncpg://jailbreak_user:jailbreak_password@jailbreak_db/jailbreak_db
    env_file:
      - ../fastapi-sourcemod/fastapi_sourcemod/.env
    depends_on:
      jailbreak_db:
        condition: service_started
    restart: always
    networks:
      - shark

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: qwizi@test.pl
      PGADMIN_DEFAULT_PASSWORD: test123456
    depends_on:
      - db
      - jailbreak_app
    networks:
      - shark
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  shark:
    name: shark
    external: true

volumes:
  pgadmin-data:
  local_pgdata: