"""empty message

Revision ID: 84f86db71ec9
Revises: 
Create Date: 2023-10-25 21:25:26.958374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f86db71ec9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_admins',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authtype', sa.String(length=5), nullable=True),
    sa.Column('identity', sa.String(length=65), nullable=False),
    sa.Column('password', sa.String(length=65), nullable=False),
    sa.Column('flags', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('immunity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sm_admins')
    # ### end Alembic commands ###
