"""empty message

Revision ID: 8f8698d040c3
Revises: f4aecbb18f74
Create Date: 2023-11-19 17:52:35.070261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8698d040c3'
down_revision: Union[str, None] = 'f4aecbb18f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfg_key', sa.String(length=64), nullable=False),
    sa.Column('cfg_value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sm_group_immunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('other_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sm_group_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=7), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('access', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['sm_groups.id'], name='fk_sm_group_overrides_sm_groups_id_group'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sm_group_overrides')
    op.drop_table('sm_group_immunity')
    op.drop_table('sm_config')
    # ### end Alembic commands ###
