"""empty message

Revision ID: a2a2320d065a
Revises: d5e3c62d47e1
Create Date: 2023-10-25 22:19:11.287208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a2320d065a'
down_revision: Union[str, None] = 'd5e3c62d47e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_groups',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flags', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=False),
    sa.Column('immunity_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['sm_admins.id'], name='fk_admins_groups_sm_admins_admin_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group'], ['sm_groups.id'], name='fk_admins_groups_sm_groups_group_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins_groups')
    op.drop_table('sm_groups')
    # ### end Alembic commands ###
