"""empty message

Revision ID: cdae3d3781de
Revises: 8f8698d040c3
Create Date: 2023-11-19 18:31:10.362796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdae3d3781de'
down_revision: Union[str, None] = '8f8698d040c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sm_admins_groups', 'inherit_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sm_admins_groups', 'inherit_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
