"""empty message

Revision ID: d5e3c62d47e1
Revises: 84f86db71ec9
Create Date: 2023-10-25 21:59:34.992865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e3c62d47e1'
down_revision: Union[str, None] = '84f86db71ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sm_admins', 'password',
               existing_type=sa.VARCHAR(length=65),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sm_admins', 'password',
               existing_type=sa.VARCHAR(length=65),
               nullable=False)
    # ### end Alembic commands ###
