"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersMeService = exports.UsersService = exports.SubscryptionService = exports.ServersService = exports.ScopesService = exports.RootService = exports.RolesService = exports.PlayersService = exports.ForumService = exports.AuthService = exports.AdminUsersService = exports.AdminServersAdminsService = exports.AdminServersAdminGroupsService = exports.AdminServersService = exports.AdminScopesService = exports.AdminRolesService = exports.AdminPlayersService = exports.AdminForumService = exports.ThreadActionEnum = exports.CategoryTypeEnum = exports.AuthTypeEnum = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ApiClient = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ApiClient_1 = require("./ApiClient");
Object.defineProperty(exports, "ApiClient", { enumerable: true, get: function () { return ApiClient_1.ApiClient; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var AuthTypeEnum_1 = require("./models/AuthTypeEnum");
Object.defineProperty(exports, "AuthTypeEnum", { enumerable: true, get: function () { return AuthTypeEnum_1.AuthTypeEnum; } });
var CategoryTypeEnum_1 = require("./models/CategoryTypeEnum");
Object.defineProperty(exports, "CategoryTypeEnum", { enumerable: true, get: function () { return CategoryTypeEnum_1.CategoryTypeEnum; } });
var ThreadActionEnum_1 = require("./models/ThreadActionEnum");
Object.defineProperty(exports, "ThreadActionEnum", { enumerable: true, get: function () { return ThreadActionEnum_1.ThreadActionEnum; } });
var AdminForumService_1 = require("./services/AdminForumService");
Object.defineProperty(exports, "AdminForumService", { enumerable: true, get: function () { return AdminForumService_1.AdminForumService; } });
var AdminPlayersService_1 = require("./services/AdminPlayersService");
Object.defineProperty(exports, "AdminPlayersService", { enumerable: true, get: function () { return AdminPlayersService_1.AdminPlayersService; } });
var AdminRolesService_1 = require("./services/AdminRolesService");
Object.defineProperty(exports, "AdminRolesService", { enumerable: true, get: function () { return AdminRolesService_1.AdminRolesService; } });
var AdminScopesService_1 = require("./services/AdminScopesService");
Object.defineProperty(exports, "AdminScopesService", { enumerable: true, get: function () { return AdminScopesService_1.AdminScopesService; } });
var AdminServersService_1 = require("./services/AdminServersService");
Object.defineProperty(exports, "AdminServersService", { enumerable: true, get: function () { return AdminServersService_1.AdminServersService; } });
var AdminServersAdminGroupsService_1 = require("./services/AdminServersAdminGroupsService");
Object.defineProperty(exports, "AdminServersAdminGroupsService", { enumerable: true, get: function () { return AdminServersAdminGroupsService_1.AdminServersAdminGroupsService; } });
var AdminServersAdminsService_1 = require("./services/AdminServersAdminsService");
Object.defineProperty(exports, "AdminServersAdminsService", { enumerable: true, get: function () { return AdminServersAdminsService_1.AdminServersAdminsService; } });
var AdminUsersService_1 = require("./services/AdminUsersService");
Object.defineProperty(exports, "AdminUsersService", { enumerable: true, get: function () { return AdminUsersService_1.AdminUsersService; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var ForumService_1 = require("./services/ForumService");
Object.defineProperty(exports, "ForumService", { enumerable: true, get: function () { return ForumService_1.ForumService; } });
var PlayersService_1 = require("./services/PlayersService");
Object.defineProperty(exports, "PlayersService", { enumerable: true, get: function () { return PlayersService_1.PlayersService; } });
var RolesService_1 = require("./services/RolesService");
Object.defineProperty(exports, "RolesService", { enumerable: true, get: function () { return RolesService_1.RolesService; } });
var RootService_1 = require("./services/RootService");
Object.defineProperty(exports, "RootService", { enumerable: true, get: function () { return RootService_1.RootService; } });
var ScopesService_1 = require("./services/ScopesService");
Object.defineProperty(exports, "ScopesService", { enumerable: true, get: function () { return ScopesService_1.ScopesService; } });
var ServersService_1 = require("./services/ServersService");
Object.defineProperty(exports, "ServersService", { enumerable: true, get: function () { return ServersService_1.ServersService; } });
var SubscryptionService_1 = require("./services/SubscryptionService");
Object.defineProperty(exports, "SubscryptionService", { enumerable: true, get: function () { return SubscryptionService_1.SubscryptionService; } });
var UsersService_1 = require("./services/UsersService");
Object.defineProperty(exports, "UsersService", { enumerable: true, get: function () { return UsersService_1.UsersService; } });
var UsersMeService_1 = require("./services/UsersMeService");
Object.defineProperty(exports, "UsersMeService", { enumerable: true, get: function () { return UsersMeService_1.UsersMeService; } });
