"""empty message

Revision ID: 03725c282dcd
Revises: a28f78264a0e
Create Date: 2023-04-10 15:41:14.166617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03725c282dcd'
down_revision = 'a28f78264a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_color_module', sa.Column('flag', sa.String(length=1), nullable=False))
    op.create_unique_constraint(None, 'chat_color_module', ['flag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_color_module', type_='unique')
    op.drop_column('chat_color_module', 'flag')
    # ### end Alembic commands ###
