"""empty message

Revision ID: 117496ba3ab1
Revises: 9a72d545345f
Create Date: 2023-08-01 20:27:36.589392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117496ba3ab1'
down_revision = '9a72d545345f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
