"""empty message

Revision ID: 14daa3bd4bbd
Revises: a2e058ec6f5f
Create Date: 2023-09-29 12:08:48.916420

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '14daa3bd4bbd'
down_revision = 'a2e058ec6f5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_players_users_id_user', 'players', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_players_users_id_user', 'players', type_='foreignkey')
    op.drop_column('players', 'user')
    # ### end Alembic commands ###
