"""empty message

Revision ID: 1afd1d1c8469
Revises: 8ae321bcea7b
Create Date: 2023-10-02 18:19:59.066936

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '1afd1d1c8469'
down_revision = '8ae321bcea7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
