"""empty message

Revision ID: 1bba2bc00272
Revises: 3964218754b7
Create Date: 2023-04-10 14:02:43.417510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bba2bc00272'
down_revision = '3964218754b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'points')
    op.add_column('server_stats', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_stats', 'points')
    op.add_column('player_stats', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
