"""empty message

Revision ID: 1cde8614c458
Revises: bc0effee5db2
Create Date: 2023-02-08 23:42:56.803260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cde8614c458'
down_revision = 'bc0effee5db2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('steamrep_profile', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_players_steamrep_profiles_id_steamrep_profile', 'players', 'steamrep_profiles', ['steamrep_profile'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_players_steamrep_profiles_id_steamrep_profile', 'players', type_='foreignkey')
    op.drop_column('players', 'steamrep_profile')
    # ### end Alembic commands ###
