"""empty message

Revision ID: 1dd0a4ed6a3c
Revises: 6d91814d1ba8
Create Date: 2023-07-22 15:39:40.216113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd0a4ed6a3c'
down_revision = '6d91814d1ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_online')
    # ### end Alembic commands ###
