"""empty message

Revision ID: 245e43f6ae28
Revises: 909cf6fb8367
Create Date: 2023-03-10 01:51:58.512852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245e43f6ae28'
down_revision = '909cf6fb8367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('secret_key', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'secret_key')
    # ### end Alembic commands ###
