"""empty message

Revision ID: 29cee9100685
Revises: 5d24a7ee36c2
Create Date: 2022-12-02 00:59:57.434917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cee9100685'
down_revision = '5d24a7ee36c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scopes')
    # ### end Alembic commands ###
