"""empty message

Revision ID: 30c0bcb2bb2a
Revises: 245e43f6ae28
Create Date: 2023-03-10 01:52:56.893116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c0bcb2bb2a'
down_revision = '245e43f6ae28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
