"""empty message

Revision ID: 34517fc94e07
Revises: 03725c282dcd
Create Date: 2023-04-10 15:42:07.120608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34517fc94e07'
down_revision = '03725c282dcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
