"""empty message

Revision ID: 3964218754b7
Revises: c0b40e8c0df4
Create Date: 2023-04-09 14:58:32.161992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3964218754b7'
down_revision = 'c0b40e8c0df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'date')
    # ### end Alembic commands ###
