"""empty message

Revision ID: 3ac65ba897cf
Revises: ea89ac07be5c
Create Date: 2022-12-13 00:58:09.100576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac65ba897cf'
down_revision = 'ea89ac07be5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
