"""empty message

Revision ID: 3b1c47bdee0b
Revises: 39d39fb20444
Create Date: 2023-09-15 14:30:00.135715

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '3b1c47bdee0b'
down_revision = '39d39fb20444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('threads_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('posts_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'likes_count')
    op.drop_column('users', 'posts_count')
    op.drop_column('users', 'threads_count')
    # ### end Alembic commands ###
