"""empty message

Revision ID: 45e2936a0c94
Revises: 6b59ba6f683b
Create Date: 2023-08-02 19:01:09.667063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e2936a0c94'
down_revision = '6b59ba6f683b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_categories', sa.Column('threads_count', sa.Integer(), nullable=True))
    op.add_column('forum_posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('forum_threads', sa.Column('post_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_threads', 'post_count')
    op.drop_column('forum_posts', 'likes_count')
    op.drop_column('forum_categories', 'threads_count')
    # ### end Alembic commands ###
