"""empty message

Revision ID: 4a22d6ec4e08
Revises: 20d18bb56062
Create Date: 2022-12-04 20:07:31.637818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a22d6ec4e08"
down_revision = "20d18bb56062"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("display_role", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_roles_id_display_role", "users", "roles", ["display_role"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_roles_id_display_role", "users", type_="foreignkey")
    op.drop_column("users", "display_role")
    # ### end Alembic commands ###
