"""empty message

Revision ID: 5d744818e557
Revises: b261395d18b1
Create Date: 2022-12-13 02:14:50.008512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d744818e557'
down_revision = 'b261395d18b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steamprofiles',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('steamid32', sa.String(length=255), nullable=False),
    sa.Column('steamid64', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_steamprofiles_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid32'),
    sa.UniqueConstraint('steamid64')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steamprofiles')
    # ### end Alembic commands ###
