"""empty message

Revision ID: 63f9fa9803aa
Revises: 4a95834667dd
Create Date: 2022-11-27 20:11:42.988257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63f9fa9803aa"
down_revision = "4a95834667dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_date")
    op.drop_column("users", "created_date")
    # ### end Alembic commands ###
