"""empty message

Revision ID: 6b59ba6f683b
Revises: dd8e207a4265
Create Date: 2023-08-02 18:58:00.177231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b59ba6f683b'
down_revision = 'dd8e207a4265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_reputation', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint('fk_forum_reputation_users_id_user', 'forum_reputation', type_='foreignkey')
    op.create_foreign_key('fk_forum_reputation_users_id_author', 'forum_reputation', 'users', ['author'], ['id'])
    op.drop_column('forum_reputation', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_reputation', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_forum_reputation_users_id_author', 'forum_reputation', type_='foreignkey')
    op.create_foreign_key('fk_forum_reputation_users_id_user', 'forum_reputation', 'users', ['user'], ['id'])
    op.drop_column('forum_reputation', 'author')
    # ### end Alembic commands ###
