"""empty message

Revision ID: 6d91814d1ba8
Revises: 7b227744ba59
Create Date: 2023-06-07 19:43:00.564372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d91814d1ba8'
down_revision = '7b227744ba59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_reputation', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_reputation', sa.Column('type', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
