"""empty message

Revision ID: 734c6e2e11f2
Revises: c52617d2ae9e
Create Date: 2023-10-02 17:11:05.040423

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '734c6e2e11f2'
down_revision = 'c52617d2ae9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
