"""empty message

Revision ID: 758d05a36021
Revises: af54a9da8e6c
Create Date: 2023-08-03 17:36:36.211274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758d05a36021'
down_revision = 'af54a9da8e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forum_threads_meta', 'value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('forum_threads_meta_name_key', 'forum_threads_meta', type_='unique')
    op.drop_constraint('forum_threads_meta_value_key', 'forum_threads_meta', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('forum_threads_meta_value_key', 'forum_threads_meta', ['value'])
    op.create_unique_constraint('forum_threads_meta_name_key', 'forum_threads_meta', ['name'])
    op.alter_column('forum_threads_meta', 'value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
