"""empty message

Revision ID: 7bd05d0a3a72
Revises: eb6f9660720a
Create Date: 2023-04-10 15:35:00.668107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd05d0a3a72'
down_revision = 'eb6f9660720a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
