"""empty message

Revision ID: 7d758a05b0a4
Revises: 3b3263528a90
Create Date: 2022-12-17 02:21:41.531340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d758a05b0a4'
down_revision = '3b3263528a90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steamprofiles', sa.Column('steamid3', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'steamprofiles', ['steamid3'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steamprofiles', type_='unique')
    op.drop_column('steamprofiles', 'steamid3')
    # ### end Alembic commands ###
