"""empty message

Revision ID: 878577a701c5
Revises: 8da15ffa6a68
Create Date: 2023-02-08 22:34:00.565141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '878577a701c5'
down_revision = '8da15ffa6a68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steamrep_profiles',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('steamid3', sa.String(length=255), nullable=False),
    sa.Column('steamid32', sa.String(length=255), nullable=False),
    sa.Column('steamid64', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=15), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_players_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steamid3'),
    sa.UniqueConstraint('steamid32'),
    sa.UniqueConstraint('steamid64')
    )
    op.create_table('playerstats',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_profile', sa.Integer(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('damage_taken', sa.Integer(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.Column('healing_taken', sa.Integer(), nullable=True),
    sa.Column('headshots', sa.Integer(), nullable=True),
    sa.Column('backstabs', sa.Integer(), nullable=True),
    sa.Column('dominations', sa.Integer(), nullable=True),
    sa.Column('revenges', sa.Integer(), nullable=True),
    sa.Column('captures', sa.Integer(), nullable=True),
    sa.Column('defends', sa.Integer(), nullable=True),
    sa.Column('ubers', sa.Integer(), nullable=True),
    sa.Column('teleports', sa.Integer(), nullable=True),
    sa.Column('suicides', sa.Integer(), nullable=True),
    sa.Column('sentries', sa.Integer(), nullable=True),
    sa.Column('buildings_destroyed', sa.Integer(), nullable=True),
    sa.Column('buildings_destroyed_sentry', sa.Integer(), nullable=True),
    sa.Column('buildings_destroyed_dispenser', sa.Integer(), nullable=True),
    sa.Column('buildings_destroyed_teleporter', sa.Integer(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('last_time_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server'], ['servers.id'], name='fk_playerstats_servers_id_server'),
    sa.ForeignKeyConstraint(['steam_profile'], ['players.id'], name='fk_playerstats_players_id_steam_profile'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('steamprofiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steamprofiles',
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steamid32', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('steamid64', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('profile_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('steamid3', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_steamprofiles_users_id_user'),
    sa.PrimaryKeyConstraint('id', name='steamprofiles_pkey'),
    sa.UniqueConstraint('steamid3', name='steamprofiles_steamid3_key'),
    sa.UniqueConstraint('steamid32', name='steamprofiles_steamid32_key'),
    sa.UniqueConstraint('steamid64', name='steamprofiles_steamid64_key')
    )
    op.drop_table('playerstats')
    op.drop_table('players')
    op.drop_table('steamrep_profiles')
    # ### end Alembic commands ###
