"""empty message

Revision ID: 8a9025de800e
Revises: 30c0bcb2bb2a
Create Date: 2023-03-21 00:05:08.473873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9025de800e'
down_revision = '30c0bcb2bb2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('ban_time', sa.DateTime(), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], name='fk_banned_users_id_banned_by'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_banned_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned')
    # ### end Alembic commands ###
