"""empty message

Revision ID: 909cf6fb8367
Revises: ea9b50628973
Create Date: 2023-03-10 01:49:08.779565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909cf6fb8367'
down_revision = 'ea9b50628973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'client_id',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('apps', 'client_secret',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'client_secret',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('apps', 'client_id',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
