"""empty message

Revision ID: 95b2b505bfc0
Revises: bbd72c1d634c
Create Date: 2022-12-17 22:33:38.474218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95b2b505bfc0"
down_revision = "bbd72c1d634c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("forum_threads_title_key", "forum_threads", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("forum_threads_title_key", "forum_threads", ["title"])
    # ### end Alembic commands ###
