"""empty message

Revision ID: 9a72d545345f
Revises: 1dd0a4ed6a3c
Create Date: 2023-08-01 20:23:38.144773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a72d545345f'
down_revision = '1dd0a4ed6a3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
