"""empty message

Revision ID: 9d51f18cadee
Revises: abc1a5c34802
Create Date: 2022-12-22 21:45:39.644350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d51f18cadee'
down_revision = 'abc1a5c34802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_salt', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['secret_salt'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secret_salt')
    # ### end Alembic commands ###
