"""empty message

Revision ID: a28f78264a0e
Revises: 7bd05d0a3a72
Create Date: 2023-04-10 15:37:36.234361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28f78264a0e'
down_revision = '7bd05d0a3a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat_color_module', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_color_module', type_='unique')
    # ### end Alembic commands ###
