"""empty message

Revision ID: aac3e942c39a
Revises: f5323cfdd105
Create Date: 2023-09-29 12:06:14.673760

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'aac3e942c39a'
down_revision = 'f5323cfdd105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_players_users_id_user', 'players', type_='foreignkey')
    op.drop_column('players', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_players_users_id_user', 'players', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
