"""empty message

Revision ID: abc1a5c34802
Revises: e79c07e66f0d
Create Date: 2022-12-17 22:58:24.942692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abc1a5c34802"
down_revision = "e79c07e66f0d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forum_threads", sa.Column("content", sa.Text(), nullable=False))
    op.add_column("forum_threads", sa.Column("author", sa.Integer(), nullable=True))
    op.drop_constraint(
        "fk_forum_threads_forum_posts_id_post", "forum_threads", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_forum_threads_users_id_author", "forum_threads", "users", ["author"], ["id"]
    )
    op.drop_column("forum_threads", "post")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forum_threads",
        sa.Column("post", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_forum_threads_users_id_author", "forum_threads", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_forum_threads_forum_posts_id_post",
        "forum_threads",
        "forum_posts",
        ["post"],
        ["id"],
    )
    op.drop_column("forum_threads", "author")
    op.drop_column("forum_threads", "content")
    # ### end Alembic commands ###
