"""empty message

Revision ID: af54a9da8e6c
Revises: 8d64138af50b
Create Date: 2023-08-03 17:09:54.366637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af54a9da8e6c'
down_revision = '8d64138af50b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_threads_meta',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.create_table('threads_threadmetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threadmeta', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thread'], ['forum_threads.id'], name='fk_threads_threadmetas_forum_threads_thread_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threadmeta'], ['forum_threads_meta.id'], name='fk_threads_threadmetas_forum_threads_meta_threadmeta_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('threads_tags')
    op.drop_constraint('fk_forum_threads_servers_id_server', 'forum_threads', type_='foreignkey')
    op.drop_column('forum_threads', 'server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('server', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_forum_threads_servers_id_server', 'forum_threads', 'servers', ['server'], ['id'])
    op.create_table('threads_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thread', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag'], ['forum_tags.id'], name='fk_threads_tags_forum_tags_tag_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread'], ['forum_threads.id'], name='fk_threads_tags_forum_threads_thread_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='threads_tags_pkey')
    )
    op.drop_table('threads_threadmetas')
    op.drop_table('forum_threads_meta')
    # ### end Alembic commands ###
