"""empty message

Revision ID: b261395d18b1
Revises: 3ac65ba897cf
Create Date: 2022-12-13 01:17:19.349754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b261395d18b1'
down_revision = '3ac65ba897cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_staff')
    # ### end Alembic commands ###
