"""empty message

Revision ID: bbd72c1d634c
Revises: 3d75d5abe624
Create Date: 2022-12-17 22:09:34.949564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd72c1d634c'
down_revision = '3d75d5abe624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_forum_threads_forum_categories_id_category', 'forum_threads', 'forum_categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_forum_threads_forum_categories_id_category', 'forum_threads', type_='foreignkey')
    op.drop_column('forum_threads', 'category')
    # ### end Alembic commands ###
