"""empty message

Revision ID: bdd90dc52ee1
Revises: 117496ba3ab1
Create Date: 2023-08-02 02:26:31.581721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd90dc52ee1'
down_revision = '117496ba3ab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['password_reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
