"""empty message

Revision ID: c25cf3a8e687
Revises: 1afd1d1c8469
Create Date: 2023-10-02 18:21:22.584232

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'c25cf3a8e687'
down_revision = '1afd1d1c8469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscription', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscription', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
