"""empty message

Revision ID: cb6d46cb2d2b
Revises: 9c7453c4e666
Create Date: 2023-02-11 19:06:40.161669

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cb6d46cb2d2b"
down_revision = "9c7453c4e666"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forum_special_thread_questions",
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("updated_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorys_specialthreadquestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialthreadquestion", sa.Integer(), nullable=True),
        sa.Column("category", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category"],
            ["forum_categories.id"],
            name="fk_category_stq_forum_categories_category_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["specialthreadquestion"],
            ["forum_special_thread_questions.id"],
            name="fk_categorys_stq_forum_special_thread_questions_stq_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "forum_categories", sa.Column("description", sa.Text(), nullable=True)
    )
    op.add_column(
        "forum_categories", sa.Column("type", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "forum_threads", sa.Column("status", sa.String(length=64), nullable=True)
    )
    op.add_column("forum_threads", sa.Column("server", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_forum_threads_servers_id_server",
        "forum_threads",
        "servers",
        ["server"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_forum_threads_servers_id_server", "forum_threads", type_="foreignkey"
    )
    op.drop_column("forum_threads", "server")
    op.drop_column("forum_threads", "status")
    op.drop_column("forum_categories", "type")
    op.drop_column("forum_categories", "description")
    op.drop_table("categorys_specialthreadquestions")
    op.drop_table("forum_special_thread_questions")
    # ### end Alembic commands ###
