"""empty message

Revision ID: d8513ad07a4b
Revises: ebe33cfcdc26
Create Date: 2023-08-03 19:31:42.043510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8513ad07a4b'
down_revision = 'ebe33cfcdc26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
