"""empty message

Revision ID: d858b422d74d
Revises: d8513ad07a4b
Create Date: 2023-08-03 20:53:36.708370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd858b422d74d'
down_revision = 'd8513ad07a4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_threads', 'is_pinned')
    # ### end Alembic commands ###
