"""empty message

Revision ID: dd8e207a4265
Revises: bdd90dc52ee1
Create Date: 2023-08-02 02:56:38.791309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e207a4265'
down_revision = 'bdd90dc52ee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_reset_token_key', 'users', type_='unique')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_password_reset_token_key', 'users', ['password_reset_token'])
    # ### end Alembic commands ###
