"""empty message

Revision ID: e79c07e66f0d
Revises: 95b2b505bfc0
Create Date: 2022-12-17 22:44:33.757211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79c07e66f0d'
down_revision = '95b2b505bfc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('post', sa.Integer(), nullable=True))
    op.drop_constraint('fk_forum_threads_users_id_author', 'forum_threads', type_='foreignkey')
    op.create_foreign_key('fk_forum_threads_forum_posts_id_post', 'forum_threads', 'forum_posts', ['post'], ['id'])
    op.drop_column('forum_threads', 'author')
    op.drop_column('forum_threads', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_threads', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('forum_threads', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_forum_threads_forum_posts_id_post', 'forum_threads', type_='foreignkey')
    op.create_foreign_key('fk_forum_threads_users_id_author', 'forum_threads', 'users', ['author'], ['id'])
    op.drop_column('forum_threads', 'post')
    # ### end Alembic commands ###
