"""empty message

Revision ID: ea89ac07be5c
Revises: 6f68d4e28177
Create Date: 2022-12-11 03:28:33.090026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ea89ac07be5c"
down_revision = "6f68d4e28177"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_login", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
