"""empty message

Revision ID: ea9b50628973
Revises: ed39b7404753
Create Date: 2023-03-10 01:21:10.264138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9b50628973'
down_revision = 'ed39b7404753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.String(length=16), nullable=False),
    sa.Column('client_secret', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='fk_apps_users_id_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apps_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.Column('app', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app'], ['apps.id'], name='fk_apps_scopes_apps_app_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope'], ['scopes.id'], name='fk_apps_scopes_scopes_scope_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps_scopes')
    op.drop_table('apps')
    # ### end Alembic commands ###
