"""empty message

Revision ID: ed39b7404753
Revises: cb6d46cb2d2b
Create Date: 2023-02-11 19:59:20.092362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed39b7404753'
down_revision = 'cb6d46cb2d2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_special_thread_questions', sa.Column('name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'forum_special_thread_questions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum_special_thread_questions', type_='unique')
    op.drop_column('forum_special_thread_questions', 'name')
    # ### end Alembic commands ###
