"""empty message

Revision ID: f39425298097
Revises: 7d758a05b0a4
Create Date: 2022-12-17 02:22:42.018829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39425298097'
down_revision = '7d758a05b0a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steamprofiles', sa.Column('country_code', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steamprofiles', 'country_code')
    # ### end Alembic commands ###
