from enum import Enum


class UsersExceptionsDetailEnum(str, Enum):
    USER_NOT_FOUND = "User not found"
    USERNAME_NOT_AVAILABLE = "Username not available"
    INVALID_CURRENT_PASSWORD = "Invalid current password"
    CANNOT_CHANGE_DISPLAY_ROLE = "U cannot change your display role if u don't have this role"


class UsersEventsEnum(str, Enum):
    GET_ALL_PRE = "USERS_GET_ALL_PRE"
    GET_ALL_POST = "USERS_GET_ALL_POST"
    GET_ONE_PRE = "USERS_GET_ONE_PRE"
    GET_ONE_POST = "USERS_GET_ONE_POST"
    ME_PRE = "USERS_ME_PRE"
    ME_POST = "USERS_ME_POST"
    CHANGE_USERNAME_PRE = "USERS_CHANGE_USERNAME_PRE"
    CHANGE_USERNAME_POST = "USERS_CHANGE_USERNAME_POST"
    CHANGE_PASSWORD_PRE = "USERS_CHANGE_PASSWORD_PRE"
    CHANGE_PASSWORD_POST = "USERS_CHANGE_PASSWORD_POST"
    CHANGE_DISPLAY_ROLE_PRE = "USERS_CHANGE_DISPLAY_ROLE_PRE"
    CHANGE_DISPLAY_ROLE_POST = "USERS_CHANGE_DISPLAY_ROLE_POST"
    GET_LAST_LOGGED_PRE = "USERS_GET_LAST_LOGGED_PRE"
    GET_LAST_LOGGED_POST = "USERS_GET_LAST_LOGGED_POST"
    GET_ONLINE_PRE = "USERS_GET_ONLINE_PRE"
    GET_ONLINE_POST = "USERS_GET_ONLINE_POST"


class UsersAdminEventsEnum(str, Enum):
    GET_ALL_PRE = "USERS_ADMIN_GET_ALL_PRE"
    GET_ALL_POST = "USERS_ADMIN_GET_ALL_POST"
    GET_ONE_PRE = "USERS_ADMIN_GET_ONE_PRE"
    GET_ONE_POST = "USERS_ADMIN_GET_ONE_POST"
    CREATE_PRE = "USERS_ADMIN_CREATE_PRE"
    CREATE_POST = "USERS_ADMIN_CREATE_POST"
    DELETE_PRE = "USERS_ADMIN_DELETE_PRE"
    DELETE_POST = "USERS_ADMIN_DELETE_POST"
