"""empty message

Revision ID: 5395faea6432
Revises: 817d8dae8407
Create Date: 2023-12-01 14:28:23.418445

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "5395faea6432"
down_revision = "817d8dae8407"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("servers", sa.Column("tag", sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, "servers", ["tag"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "servers", type_="unique")
    op.drop_column("servers", "tag")
    # ### end Alembic commands ###
