"""empty message

Revision ID: 5af9bcad51f2
Revises: 8eed4084692c
Create Date: 2023-09-29 12:15:25.078267

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '5af9bcad51f2'
down_revision = '8eed4084692c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_players_users_id_user', 'players', type_='foreignkey')
    op.drop_column('players', 'user')
    op.add_column('users', sa.Column('player', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_players_id_player', 'users', 'players', ['player'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_players_id_player', 'users', type_='foreignkey')
    op.drop_column('users', 'player')
    op.add_column('players', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_players_users_id_user', 'players', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
