"""empty message

Revision ID: 8eed4084692c
Revises: 14daa3bd4bbd
Create Date: 2023-09-29 12:12:27.809971

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '8eed4084692c'
down_revision = '14daa3bd4bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
