"""empty message

Revision ID: a2e058ec6f5f
Revises: aac3e942c39a
Create Date: 2023-09-29 12:06:50.010401

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'a2e058ec6f5f'
down_revision = 'aac3e942c39a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
