"""empty message

Revision ID: c52617d2ae9e
Revises: 88e4d5f117b6
Create Date: 2023-10-01 18:01:20.649676

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'c52617d2ae9e'
down_revision = '88e4d5f117b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('stripe_price_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscription', 'stripe_price_id')
    # ### end Alembic commands ###
