"""empty message

Revision ID: f5323cfdd105
Revises: 9163f57ba8cb
Create Date: 2023-09-16 21:46:20.844352

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'f5323cfdd105'
down_revision = '9163f57ba8cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('servers_ip_key', 'servers', type_='unique')
    op.create_unique_constraint(None, 'servers', ['port'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    op.create_unique_constraint('servers_ip_key', 'servers', ['ip'])
    # ### end Alembic commands ###
