"""empty message

Revision ID: fd95dc03ad22
Revises: c25cf3a8e687
Create Date: 2023-10-10 01:24:16.581730

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'fd95dc03ad22'
down_revision = 'c25cf3a8e687'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('user_ip', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_usersessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usersession', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_usersessions_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usersession'], ['user_sessions.id'], name='fk_users_usersessions_user_sessions_usersession_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_usersessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
