"""
empty message

Revision ID: 9666e912c3fb
Revises: bd6ef67f1b10
Create Date: 2023-11-26 17:36:18.384429

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9666e912c3fb"
down_revision = "bd6ef67f1b10"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("roles_name_key", "roles", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("roles_name_key", "roles", ["name"])
    # ### end Alembic commands ###
