"""
empty message

Revision ID: c72d3c31b00d
Revises: 5395faea6432
Create Date: 2023-12-04 10:57:53.374112

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c72d3c31b00d"
down_revision = "5395faea6432"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sourcemod_apis",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sourcemod_apis")
    # ### end Alembic commands ###
