name: Publish Backend Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Find last commit affecting 'backend' directory
        id: last_commit
        run: |
          LAST_COMMIT_SHA=$(git rev-list -1 HEAD -- backend/)
          echo "LAST_COMMIT_SHA=$LAST_COMMIT_SHA" >> $GITHUB_ENV

      - name: Check for changes in backend directory
        id: check_changes
        run: |
          if [ "$LAST_COMMIT_SHA" == "${{ github.sha }}" ]; then
            echo "::set-output name=backend_changed::true"
          else
            echo "::set-output name=backend_changed::false"
          fi

      - name: Log in to Docker Hub
        if: steps.check_changes.outputs.backend_changed == 'true'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.check_changes.outputs.backend_changed == 'true'
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: qwizii/sharkservers-backend
      
      - name: Build and push Docker image
        if: steps.check_changes.outputs.backend_changed == 'true'
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
