name: Publish Frontend Docker image

on:
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Check for changes in frontend directory
        id: check_changes
        run: |
          FRONTEND_CHANGED=$(git diff --name-only origin/master...${{ github.head_ref }} -- frontend/ | wc -l)
          if [ "$FRONTEND_CHANGED" -gt 0 ]; then
            echo "::set-output name=frontend_changed::true"
          else
            echo "::set-output name=frontend_changed::false"
          fi

      - name: Log in to Docker Hub
        if: steps.check_changes.outputs.frontend_changed == 'true'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.check_changes.outputs.frontend_changed == 'true'
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: qwizii/sharkservers-frontend
      
      - name: Build and push Docker image
        if: steps.check_changes.outputs.frontend_changed == 'true'
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
