name: Publish Frontend Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags
      
      - name: Get previous tag
        id: previoustag
        run: |
            git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            CURRENT_TAG=${GITHUB_REF#refs/tags/}
            PREVIOUS_TAG=$(git tag --sort=-creatordate | grep -B1 $CURRENT_TAG | head -n1)
            echo "::set-output name=previous_tag::$PREVIOUS_TAG"
  
      - name: Check for changes in frontend directory
        id: check_changes
        run: |
            if [ -n "${{ steps.previoustag.outputs.previous_tag }}" ]; then
              CHANGE_COUNT=$(git diff --name-only ${{ steps.previoustag.outputs.previous_tag }} $GITHUB_SHA -- frontend/ | wc -l)
              if [ "$CHANGE_COUNT" -gt 0 ]; then
                echo "::set-output name=frontend_changed::true"
              else
                echo "::set-output name=frontend_changed::false"
              fi
            else
              echo "::set-output name=frontend_changed::false"
            fi

      - name: Log in to Docker Hub
        if: steps.check_changes.outputs.frontend_changed == 'true'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.check_changes.outputs.frontend_changed == 'true'
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: qwizii/sharkservers-frontend
      
      - name: Build and push Docker image
        if: steps.check_changes.outputs.frontend_changed == 'true'
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
