name: Publish Package to npmjs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract version from branch name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        shell: bash

      - name: Update package.json version
        run: |
          cd js-client
          npm version $RELEASE_VERSION --no-git-tag-version
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - name: Install dependencies
        run: npm ci
        working-directory: js-client

      - name: Publish package
        run: npm publish
        working-directory: js-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}